# Generated by Django 5.2.3 on 2025-06-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('pitch_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
