# Generated by Django 5.2.3 on 2025-06-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
